### ISSUE TITLE
Adding namespace to the resources

### ISSUE THREAD

**Issue by blublinsky** [jvm-operators/abstract-operator#39]
### Describe the problem:

  * CRD contains namespace for every resource that it creates (I can see it using describe). I added a namespace to the EntityInfo assuming that during reconciliation it would be read from the CRD, but I am reading null. Am I missing something? 

#### Steps to reproduce:

  1. Add namespace to EntityInfo class
  2. Create resources
  3. Log desired resources during reconciliation
  
#### Observed Results:

  * namespace is null.
  
#### Expected Results:

  * Namespace is the namespace that can be obtained from oc describe resource

**Comment by Jiri-Kremser** [comment]
Namespace should be inferred automatically from the context. If user creates custom resource of CRD "type" in namespace X and provided the operator watches for event in this namespace, it should get notified.

One can set the environment variable `WATCH_NAMESPACE` to comma separated list of namespaces in which the operator will watch for events (it basically starts `n` those watchers where each watcher will have the `namespace` private [field](https://github.com/jvm-operators/abstract-operator/blob/62937b4e9f9a399574c8295da18963df26426385/src/main/java/io/radanalytics/operator/common/AbstractWatcher.java#L35) correctly set).

other allowed values for `WATCH_NAMESPACE` are `*` and `~`.

`~` ... run the watcher in the same namespace where the operator is deployed
`*` ... watch for the events in all the available namespaces

The case with `*` is little bit tricky. It doesn't start n threads/watchers for each exisiting namespace (it would miss the newly created namespaces and would be inefficient). Instead, it runs just [one](https://github.com/jvm-operators/abstract-operator/blob/62937b4e9f9a399574c8295da18963df26426385/src/main/java/io/radanalytics/operator/common/AbstractWatcher.java#L127) watcher that does some [magic](https://github.com/jvm-operators/abstract-operator/blob/62937b4e9f9a399574c8295da18963df26426385/src/main/java/io/radanalytics/operator/common/AbstractOperator.java#L163:L174) under the covers.

For the `*` case the operator's service account requires ClusterRole that would allow the cross-namespace "watching".

If the value of `WATCH_NAMESPACE` is empty, it [behaves](https://github.com/jvm-operators/abstract-operator/blob/62937b4e9f9a399574c8295da18963df26426385/src/main/java/io/radanalytics/operator/common/OperatorConfig.java#L79) as in `~`-case.


Could you please post here your yaml file that you use for deploying the operator? Specifically, what's the value of `WATCH_NAMESPACE` in your case.

**Comment by blublinsky** [comment]
Thanks Jirka,
I figured all this.
What i was trying to do is to get the namespace value of the resourse during reconsiliation. Trying to implement reconsiliation for * that you are skipping iñ spark

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Jiri-Kremser** [comment]
I see. There is that [getDesiredSet](https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/common/AbstractOperator.java#L348) method that can help with the full reconciliation, however the entities wont have the actual namespace on them and it wasn't actually designed for the "`*`". You can always fall back to low-lvl operations using the fabric8 client in your full reconciliation method and maintain some hash map of your entities (including the namespace). Drawback is that running an expensive full reconciliation method (where you query multiple namespaces, etc.) can have negative performance impact, but it'c certainly doable. 

If you think the `getDesiredSet` can be done better for the "*-case", feel free to open PR. Help is always welcome.

**Comment by blublinsky** [comment]
Jirka, I created PR, but I do not have a permission to add it.
Basically I have modified 2 classes:

I tested this and it works great. With this in place, I can easily implement reconciliation for the namespace “*” cause I can get not only the name, but namespace as well

Let me know if this is enough or you need something else

Boris Lublinsky
FDP Architect
boris.lublinsky@lightbend.com
https://www.lightbend.com/

**Comment by Jiri-Kremser** [comment]
> Jirka, I created PR, but I do not have a permission to add it.

I can't see the PR, you should have permissions to open a pull request. You need to fork the repository first, push the commits to your forked version and then open the PR against this repo (https://help.github.com/en/articles/creating-a-pull-request-from-a-fork)

... or post a patch here in the comment and I can test it and possibly apply

**Comment by blublinsky** [comment]
Here are the 2 changes that I had to make

[Archive.zip](https://github.com/jvm-operators/abstract-operator/files/3013618/Archive.zip)

**Comment by blublinsky** [comment]
Jiri,
Any progress on this?

**Comment by Jiri-Kremser** [comment]
well, it would be much faster, if you just opened the pull request :)
let me look into this..

**Comment by Jiri-Kremser** [comment]
ok, so the Archive.zip ^ contains two files and they are the exact copies of what is currently in this repository, check:
* https://github.com/jvm-operators/abstract-operator/blob/62937b4e9f9a399574c8295da18963df26426385/src/main/java/io/radanalytics/operator/common/Operator.java
* https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/common/AbstractWatcher.java

Seriously, if you want the change to get in, either fist consult [this](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) and then open the PR or send _only_ the patch/diff. Because even if the zip archive had the right files with your change, I'd have to create the PR from it myself.

**Comment by blublinsky** [comment]
Oh, I am sorry, wrong file
[Archive.zip](https://github.com/jvm-operators/abstract-operator/files/3029910/Archive.zip)

**Comment by blublinsky** [comment]
And I am sorry again, here is the right one
[Archive.zip](https://github.com/jvm-operators/abstract-operator/files/3029948/Archive.zip)
In the EntityInfo, namespace is added and in the custom resource watcher, convert method is updated to get namespace from CRD and map it to the resource. Both are tested.
Sorry about confusion

**Comment by Jiri-Kremser** [comment]
Thanks for the change, the PR - https://github.com/jvm-operators/abstract-operator/pull/41 You will find your changes in the next release.
