### ISSUE TITLE
Strange connection error

### ISSUE THREAD

**Issue by blublinsky** [jvm-operators/abstract-operator#40]
### Describe the problem:

  * When running an operator, I periodically getting
Mar 24, 2019 1:16:24 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://172.30.0.1/  was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

Any insight? 

#### Steps to reproduce:

  1. 
  2. 
  3. 
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?

**Comment by Jiri-Kremser** [comment]
related issues in fabric8 k8s client:
* https://github.com/fabric8io/kubernetes-client/issues/1228
* https://github.com/fabric8io/kubernetes-client/issues/1013
* https://github.com/fabric8io/kubernetes-client/issues/1090

and I can see the same issue in the spark-operator

**Comment by blublinsky** [comment]
Thanks
