### ISSUE TITLE
New implementation build on the framework

### ISSUE THREAD

**Issue by blublinsky** [jvm-operators/abstract-operator#44]
### Describe the problem:

  * I have a Flink operator https://github.com/lightbend/fdp-flink-operator build on the same framework. Feel free to add this to the reference implementation and comment on it

#### Steps to reproduce:

  1. 
  2. 
  3. 
  
#### Observed Results:

  * What happened?  This could be a description, log output, etc.
  
#### Expected Results:

  * What did you expect to happen?

**Comment by Jiri-Kremser** [comment]
Cool, you made the repo public, congrats! Added in https://github.com/jvm-operators/abstract-operator/commit/1177d93d4630a934485e33e3e7c91d3eba1a30ca
