### ISSUE TITLE
Bug in Custom resource watcher

### ISSUE THREAD

**Issue by blublinsky** [jvm-operators/abstract-operator#49]
### Describe the problem:

https://github.com/jvm-operators/abstract-operator/blob/master/src/main/java/io/radanalytics/operator/common/CustomResourceWatcher.java#L86
  
is String namespace = info.getMetadata().getName();
where it should be 
String namespace = info.getMetadata().getNamespace();

**Comment by Jiri-Kremser** [comment]
thanks, nice catch! Fixed in 815acd8
