### ISSUE TITLE
Rebase on quarkus

### ISSUE THREAD

**Issue by jkremser** [jvm-operators/abstract-operator#54]
thanks to @geoand this PR https://github.com/quarkusio/quarkus/pull/2910 has been merged and now it's much more convenient to use quarkus w/ the k8s client (and transitively the native image from graalvm)

So let's rebase the SDK on Quarkus, it also allows to use the CDI [subset](https://quarkus.io/guides/cdi-reference#supported_features). And potentially we can get rid of the way how we find the classes that have the `@Operator` annotation and use the programmatic lookup via `@Instance`

**Comment by geoand** [comment]
Sounds awesome!
